Add can_write() function

diff --git a/common b/common
--- a/common
+++ b/common
@@ -390,3 +390,15 @@ cpu_count(){
     local cpus=$(( $(cat /sys/devices/system/cpu/online | cut -c 3-) + 1 ))
     echo ${cpus}
 }
+
+can_write(){
+    local user=$1
+    local file=$2
+    if [ ! -f ${file} ]; then 
+	log "${warning} File ${file} not found"
+	return 1
+    else
+	su ${user} -c "[ -w ${file} ]"
+	return $?
+    fi
+}
