Add host IP management to container script

diff --git a/container b/container
--- a/container
+++ b/container
@@ -36,11 +36,10 @@ container_start(){
 
 container_ip_setup(){
     if [ -n "${public_ip_addr}" -a -n "${public_ip_iface}" -a -n "${public_ip_mask}" ]; then
-	ip -o addr | grep ${public_ip_addr} > /dev/null && log "${warning} Container IP already set up" && return
+	ip -o addr | grep ${public_ip_addr} > /dev/null && log "${warning} Container IP ${public_ip_addr} already set up" && return
 	ifconfig ${public_ip_iface} add ${public_ip_addr} netmask ${public_ip_mask} 
-	[ $? -ne 0 ] && log "${critical} Error setting up container IP ${public_ip_iface} ${public_ip_mask} on ${public_ip_iface}" && exit 4
+	[ $? -ne 0 ] && log "${critical} Error setting up container IP ${public_ip_addr} ${public_ip_mask} on ${public_ip_iface}" && exit 4
 	local ip_alias=$(ip addr | grep ${public_ip_addr} | awk '{print $8}')
-	echo ${ip_alias} > ${etc_dir}/container_ip_alias
 	log "${success} IP ${public_ip_iface} ${public_ip_addr} ${public_ip_mask} on ${ip_alias}"
     fi
 }
@@ -48,21 +47,21 @@ container_ip_setup(){
 
 container_ip_release(){
     if [ -n "${public_ip_addr}" ]; then
-	local self_cid=$( ${docker} ps -a | grep ${container} | cut -c1-12)
-	[ -z "${self_cid}" ] && log "${warning} No running container found" 
-	${docker} ps -q | while read cid; do
-	    if [ "${cid}" != "${self_cid}" ]; then
-		${docker} inspect ${cid} | grep ${public_ip_addr} > /dev/null && log "${warning} The IP of this container is shared by another container in this host" && return
-	    fi
+	# currently, release is called after the container has been stopped...
+	# local self_cid=$( ${docker} ps -a | grep ${container} | cut -c1-12)
+	# [ -z "${self_cid}" ] && log "${warning} No running container found" 
+	for cid in $(${docker} ps -q); do
+	    # if [ "${cid}" != "${self_cid}" ]; then
+	    ${docker} inspect ${cid} | grep ${public_ip_addr} > /dev/null && log "${warning} The IP of this container is shared by another container in this host" && return 1
+	    # fi
 	done
 	# No container is using the IP of this container
-	[ ! -f ${etc_dir}/container_ip_alias ] && log "${critical} No interface alias found" && return
-	local ip_alias=$(cat ${etc_dir}/container_ip_alias)
+	local ip_alias=$(ip addr | grep ${public_ip_addr} | awk '{print $8}')
 	ifconfig ${ip_alias} down 
 	if [ $? -eq 0 ]; then
-	    log "${success} interface ${public_ip_alias} ${public_ip_addr} released"
+	    log "${success} interface ${ip_alias} ${public_ip_addr} released"
 	else
-	    log "${critical} Error releasing interface ${public_ip_alias} ${public_ip_addr}"
+	    log "${critical} Error releasing interface ${ip_alias} ${public_ip_addr}"
 	fi
     fi
 }
@@ -121,16 +120,21 @@ case "$1" in
 	    log "${info} Stopping ${hash}..."
 	    log "${info} Stopping service..."
 	    watchdog 5 ssh -p ${ssh_port} localhost "${etc_dir}/service-manager stop" 
-	    ${docker} stop -t=15 ${hash}
-	    ${docker} rm ${hash} && container_ip_release
-	    log "${success} Stopped"
+	    ${docker} stop -t=15 ${hash} && \
+	    ${docker} rm ${hash} 
+	    if [ $? -eq 0 ]; then
+		container_ip_release
+		log "${success} Stopped"
+	    else
+		log "${critical} Problem stopping container"
+	    fi
 	else
 	    log "${critical} hashfile ${hash_file} not found"
 	    exit 2
 	fi
 	;;
     "test")
-	#container_ip_release
+	# container_ip_release
 	# container_ip_setup
 	;;
     *)
