Fix guacamole current password

diff --git a/guacamole-current-password b/guacamole-current-password
--- a/guacamole-current-password
+++ b/guacamole-current-password
@@ -9,10 +9,14 @@ readonly service_cfg=${0%/scripts*}/etc/service.cfg
 # readonly log_facility="guac-chpass"
 
 if [ $# -lt 1 ]; then
-    readonly guacamole_user=$(whoami)
+    readonly guser=$(whoami)
 else
-    readonly guacamole_user=${1}    
+    readonly guser=${1}    
 fi
 
-grep "${guacamole_user}" ${etc_dir}/guacamole/user-mapping.xml | sed 's_.* password="\([^"]*\)".*_\1_g'
-
+if grep "${guser}" ${etc_dir}/guacamole/user-mapping.xml > /dev/null; then 
+    grep "${guser}" ${etc_dir}/guacamole/user-mapping.xml | grep authorize |  sed 's_.* password="\([^"]*\)".*_\1_g'
+else
+    echo "User not found"
+    exit 1
+fi
