Fix xrdp service manager

diff --git a/xrdp-service b/xrdp-service
--- a/xrdp-service
+++ b/xrdp-service
@@ -24,33 +24,30 @@ readonly module="xrdp"
 readonly log_facility="${service}-${module}"
 
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 BASE=/services/guacamole/usr/xrdp
-DAEMON=${BASE}/sbin/xrdp
-SDAEMON=${BASE}/sbin/xrdp-sesman
-PIDDIR=${run_dir}
-SESMAN_START=yes
+PATH=${BASE}/bin:${BASE}/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+daemon=${BASE}/sbin/xrdp
+sdaemon=${BASE}/sbin/xrdp-sesman
+readonly pidfile=${run_dir}/${module}.pid
+readonly spidfile=${run_dir}/xrdp-sesman.pid
 #USERID=xrdp
 # the X11rdp backend only works as root at the moment - GH 20/03/2013
 USERID=root
-NAME=xrdp
-DESC="Remote Desktop Protocol server"
 
-test -x $DAEMON || exit 0
+test -x ${daemon} || exit 0
 
-. /lib/lsb/init-functions
+# . /lib/lsb/init-functions
 
 check_root()  {
     if [ "$(id -u)" != "0" ]; then
-        log_failure_msg "You must be root to start, stop or restart $NAME."
+        log "${error} You must be root to start, stop or restart ${module}."
         exit 4
     fi
 }
 
 force_stop() {
-
-DELAY=1
-PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
+   local DELAY=1
+   local PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
 
     for p in $PROCLIST; do
       pgrep -x $p >/dev/null && pkill  -x $p
@@ -58,113 +55,85 @@ PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
       pgrep -x $p >/dev/null && pkill -9 -x $p
     done
     # let's not kill ourselves - the init script is called xrdp as well
-    pgrep -fx $DAEMON  >/dev/null && pkill -fx $DAEMON
+    pgrep -fx ${daemon}  >/dev/null && pkill -fx ${daemon}
     sleep $DELAY
-    pgrep -fx $DAEMON  >/dev/null && pkill -9 -fx $DAEMON
+    pgrep -fx ${daemon}  >/dev/null && pkill -9 -fx ${daemon}
 
-   rm -f $PIDDIR/xrdp*.pid
+    rm -f ${pidfile} ${spidfile}
 }
-
-if [ -r /etc/default/$NAME ]; then
-   . /etc/default/$NAME
-fi
-
-# Tasks that can only be run as root
-if [ "$(id -u)" = "0" ]; then
-    # Check for pid dir
-    if [ ! -d $PIDDIR ] ; then
-        mkdir $PIDDIR
-    fi
-    chown $USERID:$USERID $PIDDIR
-fi
-
 
 case "$1" in
   start)
         check_root
         exitval=0
-        log "${info} Starting $DESC " 
-        if pidofproc -p $PIDDIR/$NAME.pid $DAEMON > /dev/null; then
-            log "${warning} ${NAME} apparently already running"
-            log_end_msg 0
-            exit 0
-        fi
-        log_progress_msg $NAME
-        start-stop-daemon --start --quiet --oknodo  --pidfile $PIDDIR/$NAME.pid \
-	    --chuid $USERID:$USERID --exec $DAEMON | logalize ${log_file}
-        exitval=$?
-	if [ "$SESMAN_START" = "yes" ] ; then
-            log_progress_msg "sesman"
-            start-stop-daemon --start --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid \
-	       --exec $SDAEMON  | logalize ${log_file}
-            value=$?
-            [ $value -gt 0 ] && exitval=$value
-        fi
+        log "${info} Starting xrdp " 
+#	if is_running ${daemon} ${pidfile}; then
+#            log "${warning} ${module} apparently already running"
+#            exit 0
+#        fi
+
+	# xrdp handles the pidfile itself
+	# daemon_start ${daemon} " " ${pidfile}
+	${daemon} 
+	status=$?
+	# xrdp-sesman handles the pidfile itself
+	# daemon_start ${sdaemon} " " ${spidfile}
+	if [ ${status} -eq 0 ]; then
+	    ${sdaemon}
+	    status=$?
+        # start-stop-daemon --start --quiet --oknodo  --pidfile $PIDDIR/$NAME.pid   --chuid $USERID:$USERID --exec $DAEMON | logalize ${log_file}
+        # exitval=$?
+        # start-stop-daemon --start --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid --exec $SDAEMON  | logalize ${log_file}
+	fi
         # Make pidfile readables for all users (for status to work)
-        [ -e $PIDDIR/xrdp-sesman.pid ] && chmod 0644 $PIDDIR/xrdp-sesman.pid
-        [ -e $PIDDIR/$NAME.pid ] && chmod 0644 $PIDDIR/$NAME.pid
-        # Note: Unfortunately, xrdp currently takes too long to create
-        # the pidffile unless properly patched
-        log_end_msg $exitval
+        [ -e ${spidfile} ] && chmod 0644 ${spidfile}
+        [ -e ${pidfile} ] && chmod 0644 ${pidfile}
+
+	log_status ${status} "${module} started" "Problem starting ${module}"
 	;;
   stop)
         check_root
-	[ -n "$XRDP_UPGRADE" -a "$RESTART_ON_UPGRADE" = "no" ] && {
-	    echo "Upgrade in progress, no restart of xrdp."
-	    exit 0
-	}
-        exitval=0
-        log_daemon_msg "Stopping RDP Session manager " 
+        log "${info} Stopping xrdp"
 
-	# !!!! daemons are not stopped...
-	kill $(cat ${PIDDIR}/xrdp-sesman.pid)
-	kill $(cat ${PIDDIR}/xrdp.pid)
-
-        log_end_msg $exitval
+	# !!!! xrdp has a -kill option. Maybe it is a better way to stop it?
+	[ -f ${spidfile} ] && kill $(cat ${spidfile})
+	[ -f ${pidfile} ] && kill $(cat ${pidfile})
+	if [ $? -eq 0 ]; then
+	    log "${info} xrdp stopped"
+	else
+	    log "${error} Problem stopping xrdp"
+	fi
+	 
 	;;
   force-stop)
 	$0 stop
 	# because it doesn't always die the right way
 	force_stop
 	;;
-  restart|force-reload)
+  restart)
         check_root
 	$0 stop
         # Wait for things to settle down
         sleep 1
 	$0 start
 	;;
-  reload)
-        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
-        log_warning_msg "cannot re-read the config file (use restart)."
-        ;;
   status)
         exitval=0
-        log_daemon_msg "Checking status of $DESC" "$NAME"
-        if pidofproc -p  $PIDDIR/$NAME.pid $DAEMON  > /dev/null; then
-            log_progress_msg "running"
-            log_end_msg 0
+
+        if is_running ${daemon} ${pidfile}; then
+            log "${info} ${DAEMON} running"
         else
-            log_progress_msg "apparently not running"
-            log_end_msg 1 || true
-            exitval=1
+            log "${warning} ${DAEMON} apparently not running"
         fi
-	if [ "$SESMAN_START" = "yes" ] ; then
-            log_daemon_msg "Checking status of RDP Session Manager" "sesman"
-            if pidofproc -p  $PIDDIR/xrdp-sesman.pid $SDAEMON  > /dev/null; then
-                log_progress_msg "running"
-                log_end_msg 0
-            else
-                log_progress_msg "apparently not running"
-                log_end_msg 1 || true
-                exitval=1
-            fi
+	if  is_running ${sdaemon} ${spidfile}; then
+            log "${info} ${SDAEMON} running"
+        else
+            log "${warning} ${SDAEMON} apparently not running"
 	fi
-        exit $exitval
+
         ;;
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+	echo "Usage: $0 {start|stop|force-stop|restart|status}" >&2
 	exit 1
 	;;
 esac
